### ISSUE TITLE
Agregar funcionalidad para eliminar elementos de la lista

### ISSUE THREAD

**Issue by angeloraso** [lauticonte/Practica5#1]
La aplicación debe tener alguna forma de eliminar elementos de la lista

**Comment by angeloraso** [comment]
**UPDATE**

- Encontré el botón para eliminar un elemento de la lista pero solo muestra el toast con el mensaje "Character removed"

<img width="175" alt="Screen Shot 2022-05-09 at 18 51 59" src="https://user-images.githubusercontent.com/15707453/167504956-a886a56d-815b-4369-96c8-4c485e0451b6.png">

**Comment by lauticonte** [comment]
Listo profe, ya se guardan los personajes en el storage y se pueden eliminar!
