### ISSUE TITLE
Guardar personajes de Rick & Morty en el almacenamiento local

### ISSUE THREAD

**Issue by angeloraso** [lauticonte/Practica5#2]
- Usar el [plugin de storage de Capacitor](https://capacitorjs.com/docs/apis/storage) para guardar la información en el almacenamiento local

**Comment by lauticonte** [comment]
Ahora los personajes se guardan en el storage cuando consume la api por primera vez, en caso de que el LocalStorage ya tenga la key con personajes cargados, la app los lee desde ahi y no llama a la api.
