### ISSUE TITLE
Notificar al usuario de que se ha eliminado correctamente un elemento de la lista con el Toast de Capacitor

### ISSUE THREAD

**Issue by angeloraso** [lauticonte/Practica5#3]
- Utilizar el [plugin del Toast de Capacitor](https://capacitorjs.com/docs/apis/toast) para notificar al usuario que se ha eliminado un elemento de la lista (en vez del componente Toast de Ionic)

**Comment by lauticonte** [comment]
Se agregó el Toast de Capacitor que avisa cuando falla el consumo de la API y cuando se elimina un personaje.

**Comment by angeloraso** [comment]
- Lautaro. El trabajo esta aprobado. 

Nota: Cuando un issue se resuelve, se debe solicitar la revisión a algún un usuario (en este caso a mi)
